env:
  browser: true
  es2021: true
extends:
  - standard
  - plugin:react/recommended
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules: {}
overrides:
  - files: ["**/*.ts", "**/*.tsx"]
    extends:
      - standard-with-typescript
      - prettier
    parserOptions:
      project: ./tsconfig.json
    rules: {}
